[pytest]

pythonpath = .
testpaths = tests --slowmo=200
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
bdd_features_base_dir = features/

addopts =
    --html=test-results/reports/report.html
    --self-contained-html
    -s
    -vv
    --alluredir=allure-results
    --clean-alluredir

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore::DeprecationWarning:gherkin.*:

# --- Logging Configuration ---
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Optional: Log to a file automatically
log_file = test-results/pytest-logs.log
log_file_level = DEBUG
log_file_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s

markers =
    skip: Skip test execution
    ui: UI E2E tests
    api: API CRUD tests
    regression: full suite
    TC: dynamic test case marker (e.g., @pytest.mark.TC1, @pytest.mark.TC2)
    login : Login Page Test
    positive_testing : Positive Testing
    negative_testing : Negative Testing
