name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      run_parallel:
        description: 'Run test in parallel?'
        required: true
        type: boolean
        default: false
      test_filter:
        description: 'Run specific test (e.g., -k "login" or -m "smoke")'
        required: false
        default: ''
      record_video:
        description: 'Record videos for failed test?'
        type: boolean
        default: false


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run pytest
        # Mapping inputs to environment variables for conftest.py
        env:
          RECORD_VIDEO: ${{github.event.inputs.record_video || 'false' }}

        # Use the input if provided, otherwise run all tests in the tests folder
        # run: pytest -v -s --disable-warnings ${{ github.event.inputs.test_filter }} tests
        run: |
          # Use standard bash if-else
          if [ "${{ inputs.run_parallel }}" = "true" ]; then
            PARALLEL_ARGS="-n auto"
          else
            PARALLEL_ARGS=""
          fi
          
          # Run pytest with the filter and parallel args
          pytest -v -s --disable-warnings $PARALLEL_ARGS ${{ inputs.test_filter }} tests/


      - name: Upload Artifacts
        if: always() # Ensures artifacts upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/videos/
            test-results/screenshots/
            test-results/reports/*.html
          if-no-files-found: warn
          retention-days: 7
